Frontend/HotelierAPI_WebUI/Controllers/BookingAdminController.cs
using HotelierAPI_EntityLayer.Concrete;
using HotelierAPI_WebUI.DTOs.BookingDTO;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HotelierAPI_WebUI.Controllers
{
    public class BookingAdminController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public BookingAdminController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7135/api/BookingAPI");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultBookingDTO>>(jsonData);
                return View(values);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AddBooking()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddBooking(CreateBookingDTO model)
        {
            if (ModelState.IsValid)
            {
                var client = _httpClientFactory.CreateClient();
                var jsonData = JsonConvert.SerializeObject(model);
                StringContent stringContent = new StringContent(jsonData, System.Text.Encoding.UTF8, "application/json");
                var responseMessage = await client.PostAsync("https://localhost:7135/api/BookingAPI", stringContent);
                if (responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        public async Task<IActionResult> DeleteBooking(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"https://localhost:7135/api/BookingAPI?id={id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> UpdateBooking(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:7135/api/BookingAPI/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var value = JsonConvert.DeserializeObject<UpdateBookingDTO>(jsonData);
                return View(value);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBooking(UpdateBookingDTO model)
        {
            if (model.Description == null) { model.Description = " "; }
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(model);
            StringContent stringContent = new StringContent(jsonData, System.Text.Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync($"https://localhost:7135/api/BookingAPI/UpdateBooking", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookingApproved(int BookingID)
        {
            var bookingApprovedDTO = new BookingApprovedDTO { BookingID = BookingID };
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(bookingApprovedDTO);
            StringContent stringContent = new StringContent(jsonData, System.Text.Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync($"https://localhost:7135/api/BookingAPI/BookingApproved?id={BookingID}", stringContent);
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BookingRejected(int BookingID)
        {
            var bookingRejectedDTO = new BookingRejectedDTO { BookingID = BookingID };
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(bookingRejectedDTO);
            StringContent stringContent = new StringContent(jsonData, System.Text.Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync($"https://localhost:7135/api/BookingAPI/BookingRejected?id={BookingID}", stringContent);
            return RedirectToAction("Index");
        }

    }
}

Frontend/HotelierAPI_WebUI/Views/BookingAdmin/Index.cshtml
@using HotelierAPI_WebUI.DTOs.BookingDTO
@model List<ResultBookingDTO>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
    int count = 0;
}
<div class="card-body">
    <div class="card-title">
        <h4>Rezervasyonlar</h4>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Müşteri</th>
                    <th>Giriş</th>
                    <th>Çıkış</th>
                    <th>Durum</th>
                    <th>Onayla!</th>
                    <th>İptal Et!</th>
                    <th>Detaylar</th>
                    <th>Güncelle</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    count++;
                    <tr>
                        <th>@count</th>
                        <td>@item.Name</td>
                        <td>@(((DateTime)item.CheckIn).ToShortDateString())</td>
                        <td>@(((DateTime)item.CheckOut).ToShortDateString())</td>
                        <td>
                            @if(@item.Status=="Onay Bekliyor!"){<span class="badge badge-warning px-2">@item.Status</span>}
                            @if(@item.Status=="Onaylandı!"){<span class="badge badge-primary px-2">@item.Status</span>}
                            @if(@item.Status=="İptal Edildi!"){<span class="badge badge-danger px-2">@item.Status</span>}</td>
                        <td>
                            <form asp-action="BookingApproved" asp-controller="BookingAdmin" method="post">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="BookingID" value="@item.BookingID" />
                                <button type="submit" class="btn btn-primary">Onayla!</button>
                            </form>
                        </td>
                        <td>
                            <form asp-action="BookingRejected" asp-controller="BookingAdmin" method="post">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="BookingID" value="@item.BookingID" />
                                <button type="submit" class="btn btn-danger">İptal Et!</button>
                            </form>
                        </td>
                        <td><a href="#" class="btn btn-outline-primary">Detaylar</a></td>
                        <td><a href="~/BookingAdmin/UpdateBooking/@item.BookingID" class="btn btn-outline-warning">Güncelle</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Frontend/HotelierAPI_WebUI/Views/BookingAdmin/UpdateBooking.cshtml
@using HotelierAPI_WebUI.DTOs.BookingDTO
@model UpdateBookingDTO
@{
    ViewData["Title"] = "UpdateBooking";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="BookingID" class="form-control" />
    <input type="hidden" asp-for="Status" class="form-control" />
    <label>Ad - Soyad</label>
    <input type="text" asp-for="Name" class="form-control" /><br />

    <label>E-Posta</label>
    <input type="text" asp-for="Mail" class="form-control" /><br />

    <label>Giriş Tarihi</label>
    <input type="date" asp-for="CheckIn" class="form-control" /><br />

    <label>Çıkış Tarihi</label>
    <input type="date" asp-for="CheckOut" class="form-control" /><br />

    <label>Yetişkin Sayısı</label>
    <input type="text" asp-for="AdultCount" class="form-control" /><br />

    <label>Çocuk Sayısı</label>
    <input type="text" asp-for="ChildCount" class="form-control" /><br />

    <label>Oda Sayısı</label>
    <input type="text" asp-for="RoomCount" class="form-control" /><br />

    <label>Özel İstekler</label>
    <textarea class="form-control" placeholder="Özel İstekler" asp-for="SpecialRequest" style="height: 150px"></textarea>
    <br />

    <label>Açıklama</label>
    <textarea class="form-control" placeholder="Açıklama" asp-for="Description" style="height: 150px"></textarea>
    <br />

    <button class="btn btn-primary">Güncelle</button>
</form>